# Generated by Django 4.2.5 on 2023-09-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phuc_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baibao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
