# Generated by Django 4.2.5 on 2023-09-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phuc_App', '0002_alter_baibao_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baibao',
            name='image',
            field=models.URLField(),
        ),
    ]
